# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/personal_sandbox',
                'doc_host': 'https://eafox.github.io',
                'git_url': 'https://github.com/eafox/personal_sandbox',
                'lib_path': 'personal_sandbox'},
  'syms': {'personal_sandbox.core': {'personal_sandbox.core.foo': ('core.html#foo', 'personal_sandbox/core.py')}}}
